name = "blockable"
main = "build/index.js"
compatibility_date = "2024-03-20"

[build]
command = "npm run build"

[site]
bucket = "./build/client"

[[d1_databases]]
binding = "DB"
database_name = "blockable"
database_id = "your-database-id"

[[durable_objects.bindings]]
name = "AGENT_STATE"
class_name = "AgentState"

[[migrations]]
tag = "v1"
new_classes = ["AgentState"]
